---
collect_and_enrich_news:
  description: >
    Execute comprehensive collection of the most recent articles from all trusted sources:
    
    COLLECTION PROCESS:
    1. Systematically search each source in {trusted_sources} for articles published in the last 24-48 hours
    2. For each article found, extract these exact data points:
       - Headline (exact text as published)
       - Publication date (convert to ISO format: YYYY-MM-DDTHH:MM:SSZ)
       - Brief description (2-3 sentence summary of the article's main point)
       - Full URL (direct link to the original article)
       - Background information (more background information about the article (if available))
       - Related developments (related developments to the article (if available))
    3. Apply initial relevance filter: prioritize articles about industry breakthroughs, innovations,
       product launches, funding announcements, research publications, regulatory changes, and partnerships
    4. Focus on content that could impact or interest someone in the {user_role} position 
       working toward {user_objective}
    
    QUALITY REQUIREMENTS:
    - Verify all URLs are accessible and point to original content
    - Ensure publication dates are accurate and recent (last 24-48 hours)
    - Write clear, factual brief descriptions without speculation
    - Collect minimum 10 articles, maximum 50 articles for manageable processing
    - Prioritize articles from authoritative industry publications over blog posts
    
    SCOPE: This task focuses ONLY on collection - do not perform deep analysis, 
    strategic assessment, or extensive background research. Keep descriptions factual and concise.
  
  expected_output: >
    A structured collection of recent articles using your existing NewsItems model.
    Each NewsItem must include:
    - headline: Exact article headline as published
    - publication_date: ISO format (YYYY-MM-DDTHH:MM:SSZ)  
    - brief_description: Factual 2-3 sentence summary of the article's main points
    - full_url: Direct URL to the original article
    - background_info: Factual 2-3 sentence background information about the article (if available)
    - related_developments: Factual 2-3 sentence related developments to the article (if available)
    
    Set total_count to the actual number of articles collected.
    Focus on collecting high-quality, recent articles that could be relevant to {user_role} 
    working toward {user_objective}, but do not perform deep analysis at this stage.
  async_execution: false
  output_file: news_collector_output.json
  agent: news_collector

analyze_and_select_stories:
  description: >
    STRATEGIC ANALYSIS AND RANKING PROCESS:
    
    PHASE 1 - DATA INGESTION:
    1. Read the news_collector output from the previous task
    2. Parse and validate all NewsItem entries
    3. Confirm successful loading of all articles
    
    PHASE 2 - CONTEXTUAL ANALYSIS:
    Evaluate each article through four strategic lenses:
    
    a) RELEVANCE SCORING (1-10):
       - Direct alignment with {user_role} responsibilities
       - Connection to {user_objective} goals
       - Applicability to organizational context
    
    b) IMPACT SCORING (1-10):
       - Potential business transformation magnitude
       - Competitive advantage implications
       - ROI and value creation potential
       - Industry disruption likelihood
    
    c) FEASIBILITY SCORING (1-10):
       - Implementation complexity for mid-size organizations
       - Resource requirements (budget, talent, time)
       - Technology maturity and readiness
       - Integration with existing systems
    
    d) TIMELINESS SCORING (1-10):
       - Urgency for {user_role} to act
       - Market timing and first-mover advantages
       - Risk of falling behind competitors
    
    PHASE 3 - STRATEGIC RANKING:
    1. Calculate composite strategic_score: 
       (relevance * 0.35) + (impact * 0.30) + (feasibility * 0.20) + (timeliness * 0.15)
    2. Sort all articles by strategic_score descending
    3. Select top 5-10 stories ensuring:
       - Diversity across relevant industry domains and topics
       - Mix of tactical and strategic opportunities
       - Balance of immediate actions and future planning
    
    PHASE 4 - INSIGHT GENERATION:
    For each selected story, generate:
    - Clear ranking rationale explaining the scores
    - 2-3 strategic takeaways specific to {user_role}
    - Priority classification (high/medium/low)
    - Recommended actions or next steps
    
  expected_output: >
    A RankedNewsAnalysis JSON object containing:
    - user_role and user_objective for context
    - analysis_timestamp (ISO format)
    - top_stories: Array of 5-10 RankedNewsItem objects, each with:
      * All original NewsItem fields (headline, publication_date, brief_description, full_url, etc.)
      * strategic_score (composite 1-10)
      * Individual scores (relevance_score, impact_score, feasibility_score, timeliness_score)
      * ranking_rationale (why this ranking)
      * strategic_takeaways (2-3 actionable insights as a list)
      * priority level (high/medium/low)
    - total_analyzed: Count of all articles evaluated
    - ranking_methodology: Brief description of the ranking approach used
  async_execution: false
  output_file: analyze_and_select_stories_output.json
  agent: strategic_analyst
  context:
  - collect_and_enrich_news